services:
  neo4j:
    image: neo4j:5.12.0
    container_name: neogm-test-neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_pagecache_size=256M
      - NEO4J_dbms_memory_heap_initial__size=256M
      - NEO4J_dbms_memory_heap_max__size=512M
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:7474"]
      interval: 5s
      timeout: 3s
      retries: 5